events {
    worker_connections 20000;
}
stream {
    upstream mdns_websocket {
        hash $remote_addr;
        server mdns-rr-node1:8080;
        server mdns-rr-node2:8080;
        server mdns-rr-node3:8080;
    }

    server {
        listen 8080;
        proxy_pass mdns_websocket;
        proxy_timeout 3s;
        proxy_connect_timeout 1s;
    }
}