[package]
name = "relay-server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
libp2p = { workspace = true, features = ["tokio", "noise", "macros", "ping", "tcp", "identify", "yamux", "relay", "quic"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
futures = { workspace = true }
