[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
futures = { workspace = true }
libp2p = { version = "0.56.0", features = ["tokio", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux", "quic"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
log = { workspace = true }
env_logger = { workspace = true }
uuid = { version = "1.17.0", features = ["v4"] }
